# Generated by Django 2.2.4 on 2019-08-07 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
