# Generated by Django 2.2.4 on 2019-08-08 23:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
